version: "3.0"
services:
  db_lab2:
    container_name: "db_lab2"
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lab2
    ports:
      - "5444:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: