"""new_tables

Revision ID: 33125c9eb94f
Revises: ee4a185ee286
Create Date: 2023-12-10 22:58:56.119743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33125c9eb94f'
down_revision = 'ee4a185ee286'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('reaction_type', sa.Enum('LOGGING', 'SIGNAL', 'CALL', 'SIREN', 'FIRE_SYSTEM', name='reactionchoose'), server_default='LOGGING', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('calling_to_emergency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emergency_telephone', sa.Enum('FIRE', 'POLICE', 'EMERGENCY', 'COMMON', name='emergencytelephonenumber'), nullable=False),
    sa.Column('message', sa.String(length=250), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('message', sa.String(length=250), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('available_sensors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_sensors',
    sa.Column('sensor_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('sensor_id', name='available_sensors_pkey')
    )
    op.drop_table('log')
    op.drop_table('calling_to_emergency')
    op.drop_table('sensor')
    # ### end Alembic commands ###
