"""1

Revision ID: 358d62dc8ea8
Revises: 705d73d1a2ac
Create Date: 2023-12-11 00:29:15.088194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358d62dc8ea8'
down_revision = '705d73d1a2ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
