"""1

Revision ID: 5b8a75ed57fb
Revises: c061be97861f
Create Date: 2023-12-11 00:14:06.316665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8a75ed57fb'
down_revision = 'c061be97861f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
