"""1

Revision ID: 705d73d1a2ac
Revises: 5b8a75ed57fb
Create Date: 2023-12-11 00:28:03.618894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705d73d1a2ac'
down_revision = '5b8a75ed57fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
