"""1

Revision ID: c6c0aa0e994f
Revises: 358d62dc8ea8
Create Date: 2023-12-11 00:45:21.244521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c0aa0e994f'
down_revision = '358d62dc8ea8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
