"""1

Revision ID: dbbabf755a45
Revises: decd94bb0d37
Create Date: 2023-12-11 00:07:51.502491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbbabf755a45'
down_revision = 'decd94bb0d37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
