"""1

Revision ID: ee4a185ee286
Revises: 
Create Date: 2023-12-03 21:02:19.881874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4a185ee286'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_sensors',
    sa.Column('sensor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('sensor_id'),
    sa.UniqueConstraint('sensor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('available_sensors')
    # ### end Alembic commands ###
