"""1

Revision ID: f58b93e1fd78
Revises: 
Create Date: 2023-12-12 19:29:55.212535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58b93e1fd78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('reaction_type', sa.Enum('LOGGING', 'SIGNAL', 'CALL', 'SIREN', 'FIRE_SYSTEM', name='reactionchoose'), server_default='LOGGING', nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('calling_to_emergency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emergency_telephone', sa.Enum('T_101', 'T_102', 'T_103', 'T_911', name='emergencytelephonenumber'), nullable=True),
    sa.Column('message', sa.String(length=250), nullable=True),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('message', sa.String(length=250), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    op.drop_table('calling_to_emergency')
    op.drop_table('sensor')
    # ### end Alembic commands ###
